[package]
name = "myblog"
version = "0.1.0"
authors = ["Administrator <ziyoulu1993@163.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.5"
actix-files = "0.1.4"
actix-session = "0.2.0"
bytes = "0.4.12"
futures = "0.1.28"
ring = "0.14.6"
actix-rt = "0.2.4"
env_logger = "0.6.2"

