[package]
name = "myblog"
version = "0.1.0"
authors = ["Administrator <ziyoulu1993@163.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.5"
actix-files = "0.1.4"
futures = "0.1.28"
bytes = "0.4.12"
actix-http = "0.2.7"
handlebars = "2.0.1"
serde_json = "1.0.40"
